[[todos]]
title = "更新時刻による並べ替え"
description = ""
updated_utc_datetime_rfc3339 = "2022-08-27T04:06:53.125629+00:00"

[[todos]]
title = "ファイルの書き込み方法"
description = "tomlファイルを直接上書きするのではなく(fs::createを使わず)、一時ファイルにコピーしてから削除するようにする。"
updated_utc_datetime_rfc3339 = "2022-08-27T04:08:09.964214+00:00"

[[todos]]
title = "tuiの作成"
description = "richな編集ができるtuiを作成する"
updated_utc_datetime_rfc3339 = "2022-08-27T04:08:47.269182+00:00"

[[todos]]
title = "finish関数の作成"
description = "git todos finishを呼び出すことでcommitをできるようにする"
updated_utc_datetime_rfc3339 = "2022-08-27T04:12:29.052678+00:00"

[[todos]]
title = "独自エラーの定義"
description = ""
updated_utc_datetime_rfc3339 = "2022-08-27T04:14:00.850857+00:00"
